pipeline {
    triggers {
      cron('* 01 * * *')
    }
    agent {
      node {
        label 'worker_openstack'
      }
    }

    stages {
        stage('Pull latest dev') {
            steps {
              sh 'ssh -t ubuntu@195.225.13.24 ssh root@10.20.17.19 "docker pull includeos/includeos-common:dev"'
            }
        }
        stage('Deploy microLB') {
            environment {
              MOTHERSHIP_CREDS = credentials('63505852-a03d-4db8-b312-8e7f7f493aad')
            }
            steps {
                sh '''
                  set +x
                  $HOME/mothership-beta/mothership-linux-amd64 -T --host mothership.includeos.org --username $MOTHERSHIP_CREDS_USR --password $MOTHERSHIP_CREDS_PSW images
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Register monitor job'
                echo 'Start load towards microlb'
                echo 'If no failures are detected it will report success after 23:30 hours'
            }
        }
    }
}
