#!/bin/sh

LEAF=$(pwd | awk -F\/ '{print $(NF-1) "/" $(NF)}')

if [ $LEAF = "IncludeOS/test" ]; then
	mkdir coverage && cd coverage
	cmake .. -DCOVERAGE=ON
	make && ./unittests
	lcov -c -d . -o cov.info
  lcov -r cov.info '*/unit/**' '*/usr/include/*' '*/lest/*' '*lest_util*' '*mod/GSL/*' '*mod/http-parser/*' -o cov2.info
	genhtml cov2.info -o cov
	echo "Open coverage/cov/index.html in a browser to see coverage info"

else
	echo "Run this script from the IncludeOS/test folder"
	exit 1
fi;
